query:
  name: "Query AI Agent with Home Assistant context"
  description: "Run a custom prompt with the AI Agent using your HA state dump."
  fields:
    prompt:
      description: "The question or instruction to send to the AI Agent."
      example: "Which rooms have lights on?"
